[loggers]
keys=root

[handlers]
keys=stream_handler,file_handler

[formatters]
keys=log_formatter

[logger_root]
propagate=0
level=INFO
handlers=stream_handler,file_handler

[formatter_log_formatter]
format=%(asctime)s - %(module)s %(funcName)s:%(lineno)d - [%(levelname)s] - %(message)s

[handler_stream_handler]
class=StreamHandler
level=NOTSET
formatter=log_formatter
args=(sys.stdout,)

[handler_file_handler]
class=logging.FileHandler
level=NOTSET
args=('/var/log/analyzer.log','a')
formatter=log_formatter