"""add_task_history_table

Revision ID: ca4faffec7a4
Revises: 3a504cb59752
Create Date: 2025-08-20 11:37:30.657177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4faffec7a4'
down_revision = '3a504cb59752'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
